server:
  port: 9002
  
logging:
  level:
    org:
      springframework: INFO
    com:
      valtech: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/cartservice
    username: h2
    password: password
    
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: CARTSERVICE
 
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost