server:
  port: 9091 #port
  
logging:
  level:
    org:
      springframework: INFO
    com:
      valtech: DEBUG
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/txservice #Db
    username: root
    password: root

  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      
  application:
    name: TX-SERVICE
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
    
      
